apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-kind-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-kind-app
  template:
    metadata:
      labels:
        app: multi-kind-app
    spec:
      containers:
      - name: multi-kind-app
        image: keploy/multi-kind-app:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URI
          value: "mongodb://mongoDb:27017"
        - name: REDIS_ADDR
          value: "redisDb:6379"
        - name: PORT
          value: "8080"
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: multi-kind-app-svc
  namespace: default
spec:
  selector:
    app: multi-kind-app
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: multi-kind-app-headless
  namespace: default
spec:
  clusterIP: None
  selector:
    app: multi-kind-app
  ports:
  - port: 8080
    targetPort: 8080
